#!/usr/bin/env php
<?php
/*
 * This file is part of the {{ }} package.
 *
 * (c) Yo-An Lin <cornelius.howl@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */
require 'vendor/autoload.php';

class BarCommand extends CLIFramework\Command {

    public function brief() { return 'brief of bar'; }

    public function options($opts) {
        $opts->add('v','verbose flag')->is('boolean');
        $opts->add('x|extra','extra flag');
        $opts->add('f|file:','file option')->is('file');
    }
    public function execute($user,$repo) {
        $this->getLogger()->notice('executing bar command.');
    }
}
class FooCommand extends CLIFramework\Command { 

    public function brief() { return 'brief of foo'; }

    public function execute() {
        $this->getLogger()->warn('executing foo command.');
    }
}

class ExampleApplication extends CLIFramework\Application {

    public function init()
    {
        parent::init();
        $this->registerCommand('foo','FooCommand');
        $this->registerCommand('bar','BarCommand');
    }
}


$app = new ExampleApplication;
$app->run($argv);
